name: Main Workflow

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    environment:
      name: ${{ github.ref }}
    env:
      NIX_CACHE_S3: s3://nixed/cache?profile=nix-cache&scheme=https
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Create secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NIX_CACHE_PRIVATE_KEY: ${{ secrets.NIX_CACHE_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.aws
          cat <<EOF > ~/.aws/credentials
          [nix-cache]
          aws_access_key_id = ${AWS_ACCESS_KEY_ID}
          aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
          EOF

          if [[ "${NIX_CACHE_PRIVATE_KEY}" != "" ]]; then
            mkdir ~/.secrets
            printenv NIX_CACHE_PRIVATE_KEY > ~/.secrets/nix-cache-key
          fi


      - uses: nixbuild/nix-quick-install-action@v7
        with:
          nix_version: 2.4pre20210908_3c56f62
          nix_conf: |
            experimental-features = nix-command flakes
            substituters = ${{ env.NIX_CACHE_S3 }} https://cache.nixos.org/
            trusted-users = root runner
            trusted-public-keys = nix-cache:jxOpK2dQOv/7JIb5/30+W4oidtUgmFMXLc/3mC09mKM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

      - name: Info
        run: |
          nix show-derivation
          nix path-info || true

      - name: Build dev env
        run: nix build .#devEnv -L --no-link

      - name: Check
        run: nix develop -c ./cli.sh code_quality

      - name: Fetch deno dependencies
        run: |
          export DENO_DIR=$PWD/.deno
          nix develop -c ./cli.sh update_cache
          git add "${DENO_DIR}"

      - name: Build
        run: nix build -L --no-link

      - name: Update shell nix cache
        if: github.ref == 'refs/heads/main'
        run: |
          nix store sign -r .#devEnv -k ~/.secrets/nix-cache-key -v
          nix copy .#devEnv --to '${{ env.NIX_CACHE_S3 }}' -v

      - name: Update nix cache
        if: github.ref == 'refs/heads/main'
        run: |
          nix store sign -r -k ~/.secrets/nix-cache-key -v
          nix copy --to '${{ env.NIX_CACHE_S3 }}' -v